// Generated by CoffeeScript 1.8.0
(function() {
  $(window).trigger('resize').trigger('scroll');

  $(document).ready(function() {
    return document.querySelector('#nav-toggle').addEventListener('click', function() {
      return this.classList.toggle('active');
    });
  });

}).call(this);
